Update Calculate RS.yml

diff --git a/.github/workflows/Calculate RS.yml b/.github/workflows/Calculate RS.yml
--- a/.github/workflows/Calculate RS.yml
+++ b/.github/workflows/Calculate RS.yml
@@ -81,8 +81,8 @@ jobs:
         run: |
           git config --global user.name "GitHub Action"
           git config --global user.email "action@github.com"
-          git add logs/failed_tickers.log
-          git commit -m "Add failed_tickers.log for partition ${{ matrix.partition }} on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
+          git add logs/fetchRS_failed_tickers.log
+          git commit -m "Add fetchRS_failed_tickers.log for partition ${{ matrix.partition }} on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
           git push
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -204,13 +204,6 @@ jobs:
             --log-file logs/RSCalculation_failed_tickers.log \
             --metadata-file data/ticker_price.json
 
-      - name: 📃 Archive rs_stocks.csv
-        run: |
-          mkdir -p archive
-          current_date=$(date -u -d "4 hours ago" +"%m%d%Y")
-          cp data/rs_stocks.csv archive/rs_stocks_${current_date}.csv
-          find archive -type f -name "rs_stocks_*.csv" -mtime +90 -delete
-
       - name: 🗓️ Upload outputs
         uses: actions/upload-artifact@v4
         with:
@@ -220,11 +213,19 @@ jobs:
             logs/failed_tickers.log
             archive/*.csv
             
+      - name: Archive rs_stocks.csv
+        run: |
+          mkdir -p archive
+          current_date=$(date -u -d "4 hours ago" +"%m%d%Y")
+          cp data/rs_stocks.csv archive/rs_stocks_${current_date}.csv
+          # Delete files older than 90 days
+          find archive -type f -name "rs_stocks_*.csv" -mtime +90 -delete
+
       - name: Commit outputs
         run: |
           git config user.name "github-actions"
           git config user.email "actions@users.noreply.github.com"
-          git add data/rs_stocks.csv data/rs_industries.csv data/RSRATING.csv
+          git add data/rs_stocks.csv data/rs_industries.csv data/RSRATING.csv logs/failed_tickers.log archive/rs_stocks_*.csv
           edt_time=$(date -u -d "4 hours ago" +"%I:%M %p EDT on %A, %B %d, %Y")
-          git commit -m "Generate RS CSVs [${edt_time}]" || echo "No changes to commit"
-          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed"      
+          git commit -m "Generate RS CSVs and archive rs_stocks_${current_date}.csv [${edt_time}]" || echo "No changes to commit"
+          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "Push failed"
